export const GET_MEMBERS = "GET_MEMBERS";
export const VIEW_MEMBER = "VIEW_MEMBER";
export const ADD_MEMBER = "ADD_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const UPDATE_MEMBER = "UPDATE_MEMBER";
export const GET_MEMBER_BY_ID = "GET_MEMBER_BY_ID";
export const GET_STRUCTER_BY_ID = "GET_STRUCTER_BY_ID";

export const GET_STRUCTERS = "GET_STRUCTERS";
export const VIEW_STRUCTER = "VIEW_STRUCTER";
export const ADD_STRUCTER = "ADD_STRUCTER";
export const DELETE_STRUCTER = "DELETE_STRUCTER";
export const UPDATE_STRUCTER = "UPDATE_STRUCTER";